"""Mock AI/Bot Detection Service."""

import re

async def analyze_submission(solution_content: str, user_skill: str, task_difficulty: str) -> dict:
    """
    Analyzes a task submission to determine if it was likely generated by an AI.
    Returns a score between 0.0 and 1.0 (1.0 = highly likely AI).
    """
    score = 0.1
    triggers = []

    # Check length
    if len(solution_content) < 50:
        score += 0.2
        triggers.append("Extremely short submission content (<50 chars).")

    # Check for obvious AI hallmarks
    ai_keywords = r'(?i)\b(openai|chatgpt|as an ai|language model|knowledge cutoff)\b'
    if re.search(ai_keywords, solution_content):
        score += 0.5
        triggers.append("Obvious AI hallmark keywords detected ('OpenAI', 'ChatGPT', etc).")

    # Mismatched skill to difficulty ratio
    if user_skill == "absolute_beginner" and task_difficulty == "expert":
        score += 0.4
        triggers.append("Suspiciously high performance (Beginner solving Expert task).")
        
    if task_difficulty == "beginner" and user_skill == "advanced":
        score -= 0.2
        triggers.append("Advanced user doing beginner task (score reduced).")

    # Clamp the score between 0.0 and 1.0
    final_score = max(0.0, min(1.0, score))
    is_flagged = final_score >= 0.75

    reason_str = " | ".join(triggers) if triggers else "No suspicious triggers detected."

    return {
        "score": round(final_score, 2),
        "is_flagged": is_flagged,
        "reason": reason_str
    }
