"""Add sample_solution to tasks

Revision ID: 8e8316e89d0c
Revises: c9e3c7e8e443
Create Date: 2026-02-25 13:44:45.612573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e8316e89d0c'
down_revision: Union[str, None] = 'c9e3c7e8e443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('sample_solution', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'sample_solution')
    # ### end Alembic commands ###
