"""add is_weekly boolean to tasks

Revision ID: 9bb8b8da5f50
Revises: 8e8316e89d0c
Create Date: 2026-02-26 17:16:11.369849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bb8b8da5f50'
down_revision: Union[str, None] = '8e8316e89d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_weekly', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_weekly')
    # ### end Alembic commands ###
