"""Add ai flags to task_submissions

Revision ID: c9e3c7e8e443
Revises: 9a7536de47c6
Create Date: 2026-02-25 13:12:20.371658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9e3c7e8e443'
down_revision: Union[str, None] = '9a7536de47c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('badges', 'condition_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('notifications', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.add_column('task_submissions', sa.Column('is_ai_flagged', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('task_submissions', sa.Column('ai_flag_score', sa.Float(), nullable=True))
    op.add_column('task_submissions', sa.Column('ai_flag_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_submissions', 'ai_flag_reason')
    op.drop_column('task_submissions', 'ai_flag_score')
    op.drop_column('task_submissions', 'is_ai_flagged')
    op.alter_column('notifications', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('badges', 'condition_value',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###
